version: "3.8"
services:
  nginx:
    image: nginx:1.23
    volumes:
      - ../front-end/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always

  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=khoaluan
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3307:3306"
    expose:
      - 3306

  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    restart: unless-stopped

  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql
      # - FRONTEND_URL=http://localhost
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db-mysql
