version: "3.8"
services:
  nginx:
    image: nginx:1.23
    volumes:
      - ../front-end/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:808
      - 443:443
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=khoaluan
      - MYSQL_ROOT_PASSWORD=Ocvittot123
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - ../backup/:/var/lib/mysql

  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql
      - DB_USER=root
      - DB_PASSWORD=Ocvittot123 
      - DB_NAME=khoaluan 
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db-mysql
    volumes:
      - ../backup/:/var/lib/mysql
